"""
This type stub file was generated by pyright.
"""

from .base import BaseEntity

class Album(BaseEntity):
    """An album from the Genius.com database."""
    def __init__(self, client, json_dict, tracks) -> None:
        ...
    
    def to_dict(self):
        ...
    
    def to_json(self, filename=..., sanitize=..., ensure_ascii=...): # -> str | None:
        ...
    
    def to_text(self, filename=..., sanitize=...): # -> None:
        ...
    
    def save_lyrics(self, filename=..., extension=..., overwrite=..., ensure_ascii=..., sanitize=..., verbose=...): # -> None:
        ...
    


class Track(BaseEntity):
    """docstring for Track"""
    def __init__(self, client, json_dict, lyrics) -> None:
        ...
    
    def to_dict(self):
        ...
    
    def to_json(self, filename=..., sanitize=..., ensure_ascii=...): # -> str | None:
        ...
    
    def to_text(self, filename=..., sanitize=...): # -> None:
        ...
    
    def save_lyrics(self, filename=..., extension=..., overwrite=..., ensure_ascii=..., sanitize=..., verbose=...): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


