"""
This type stub file was generated by pyright.
"""

class Sender:
    """Sends requests to Genius."""

    API_ROOT = ...
    PUBLIC_API_ROOT = ...
    WEB_ROOT = ...
    def __init__(
        self,
        access_token=...,
        response_format=...,
        timeout=...,
        sleep_time=...,
        retries=...,
        public_api_constructor=...,
        user_agent=...,
        proxy=...,
    ) -> None: ...

def get_description(e):  # -> str:
    ...
