"""
This type stub file was generated by pyright.
"""

class AlbumMethods:
    """Album methods of the public API."""
    def album(self, album_id, text_format=...):
        """Gets data for a specific album.

        Args:
            album_id (:obj:`int`): Genius album ID
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        Examples:
            .. code:: python

                genius = Genius(token)
                song = genius.search_song(378195)
                album_id = song['album']['id']
                album = genius.album(album_id)
                print(album['name'])

        """
        ...
    
    def albums_charts(self, time_period=..., chart_genre=..., per_page=..., page=..., text_format=...):
        """Gets the album charts.

        Alias for :meth:`charts() <PublicAPI.charts>`.

        Args:
            time_period (:obj:`str`, optional): Time period of the results
                ('day', 'week', 'month' or 'all_time').
            chart_genre (:obj:`str`, optional): The genre of the results.
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...
    
    def album_comments(self, album_id, per_page=..., page=..., text_format=...):
        """Gets the comments on an album page.

        Args:
            album_id (:obj:`int`): Genius album ID
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...
    
    def album_cover_arts(self, album_id, text_format=...):
        """Gets cover arts of a specific album.

        Alias for :meth:`cover_arts <PublicAPI.cover_arts>`.

        Args:
            album_id (:obj:`int`): Genius album ID
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain'). Defines the text
                formatting for the annotation of the cover arts,
                if there are any.

        Returns:
            :obj:`dict`

        Examples:
            Downloading album's cover art:

            .. code:: python

                import requests

                genius = Genius(token)
                res = genius.album_cover_arts(104614)
                cover_art = requests.get(res['cover_arts'][0]['image_url'])

        """
        ...
    
    def album_leaderboard(self, album_id, per_page=..., page=...):
        """Gets the leaderboard of an album.

        This method returns the album's top contributors.

        Args:
            album_id (:obj:`int`): Genius album ID
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).

        Returns:
            :obj:`dict`

        """
        ...
    
    def album_tracks(self, album_id, per_page=..., page=..., text_format=...):
        """Gets the tracks of a specific album.

        Args:
            album_id (:obj:`int`): Genius album ID
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...
    


