"""
This type stub file was generated by pyright.
"""

class ArticleMethods:
    """Article methods of the public API."""
    def article(self, article_id, text_format=...):
        """Gets data for a specific article.

        Args:
            article_id (:obj:`int`): Genius article ID
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...

    def article_comments(self, article_id, per_page=..., page=..., text_format=...):
        """Gets the comments on an article.

        Args:
            article_id (:obj:`int`): Genius article ID
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...

    def latest_articles(self, per_page=..., page=..., text_format=...):
        """Gets the latest articles on the homepage.

        This method will return the featured articles that are placed
        on top of the Genius.com page.

        Args:
            article_id (:obj:`int`): Genius article ID
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...
