"""
This type stub file was generated by pyright.
"""

class SearchMethods:
    """Search methods of the public API."""
    def search(self, search_term, per_page=..., page=..., type_=...):
        """Searches Genius.

        Args:
            search_term (:obj:`str`): A term to search on Genius.
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').
            type_ (:obj:`str`, optional): Type of item to search for
                ('song', 'lyric', 'artist', 'album', 'video',
                'article', 'user' or 'multi').

        Returns:
            :obj:`dict`

        .. Note::
            Specifying no :obj:`type_` parameter (which defaults to ``''``) or
            setting it as ``song`` will return the same results. Both will return
            songs. The only different is they return the hits in different
            keys:

                * ``type_=''``: ``response['hits']``
                * ``type_='song'``: ``response['sections'][0]['hits']``

            By Setting the type as ``multi`` the method will perform a search
            for all the other types and return an extra section called ``top hits``.

        .. Note::
            Instead of calling this method directly and specifying a type, you
            can use the alias methods.

        """
        ...

    def search_albums(self, search_term, per_page=..., page=...):
        """Searches the albums on Genius.

        Alias for :meth:`search() <PublicAPI.search>`

        Args:
            search_term (:obj:`str`): A term to search on Genius
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...

    def search_articles(self, search_term, per_page=..., page=...):
        """Searches the articles on Genius.

        Alias for :meth:`search() <PublicAPI.search>`

        Args:
            search_term (:obj:`str`): A term to search on Genius
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...

    def search_artists(self, search_term, per_page=..., page=...):
        """Searches the artists on Genius.

        Alias for :meth:`search() <PublicAPI.search>`

        Args:
            search_term (:obj:`str`): A term to search on Genius
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...

    def search_lyrics(self, search_term, per_page=..., page=...):
        """Searches the lyrics on Genius.

        Alias for :meth:`search() <PublicAPI.search>`

        Args:
            search_term (:obj:`str`): A term to search on Genius
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...

    def search_songs(self, search_term, per_page=..., page=...):
        """Searches the songs on Genius.

        Alias for :meth:`search() <PublicAPI.search>`

        Args:
            search_term (:obj:`str`): A term to search on Genius
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...

    def search_users(self, search_term, per_page=..., page=...):
        """Searches the users on Genius.

        Alias for :meth:`search() <PublicAPI.search>`

        Args:
            search_term (:obj:`str`): A term to search on Genius
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...

    def search_videos(self, search_term, per_page=..., page=...):
        """Searches the videos on Genius.

        Alias for :meth:`search() <PublicAPI.search>`

        Args:
            search_term (:obj:`str`): A term to search on Genius
            per_page (:obj:`int`, optional): Number of results to
                return per request. It can't be more than 50.
            page (:obj:`int`, optional): Paginated offset (number of the page).
            text_format (:obj:`str`, optional): Text format of the results
                ('dom', 'html', 'markdown' or 'plain').

        Returns:
            :obj:`dict`

        """
        ...

    def search_all(self, search_term, per_page=..., page=...):
        """Searches all types.

        Including: albums, articles, lyrics, songs, users and
        videos.

        Alias for :meth:`search() <PublicAPI.search>`

        Args:
            search_term (:obj:`str`): A term to search on Genius.
            per_page (:obj:`int`, optional): Number of results to
                return per page. It can't be more than 5 for this method.
            page (:obj:`int`, optional): Number of the page.

        Returns:
            :obj:`dict`

        Note:
            This method will also return a ``top hits`` section
            alongside other types.

        """
        ...
