"""
This type stub file was generated by pyright.
"""

import sys
from lyricsgenius.api import API, PublicAPI
from lyricsgenius.auth import OAuth2
from lyricsgenius.genius import Genius
from lyricsgenius.utils import auth_from_environment

"""A library that provides a Python interface to the Genius API"""
