"""
This type stub file was generated by pyright.
"""

class Searcher:
    """Executes the search specified by the CLI args"""
    def __init__(self, api, search_type) -> None:
        ...
    
    def __call__(self, args): # -> None:
        ...
    


def main(args=...): # -> None:
    ...

if __name__ == "__main__":
    ...
