from __future__ import annotations

from pathlib import Path
from typing import Any, AsyncGenerator, Awaitable, Mapping, Protocol, Sequence, TYPE_CHECKING

from core.enums import ArtType, Codec

if TYPE_CHECKING:
    from core.dbmodels import DBFile


class AsyncSessionLike(Protocol):
    async def exec(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_one(self, *args: Any, **kwargs: Any) -> Any: ...
    def add(self, instance: Any) -> None: ...
    async def delete(self, instance: Any) -> None: ...
    async def commit(self) -> None: ...
    async def close(self) -> None: ...
    async def refresh(self, instance: Any) -> None: ...
    def query(self, *args: Any, **kwargs: Any) -> Any: ...
    def merge(self, instance: Any) -> Any: ...


class MediaParserProtocol(Protocol):
    async def parse(self, file_path: Path) -> dict[str, Any] | None: ...


class SpatializerUtilProtocol(Protocol):
    async def widen(self, file: Path, widen_percent: float = 10.0) -> None: ...


class SilenceTrimmerProtocol(Protocol):
    async def trim(self, file: Path, codec: Codec) -> None: ...


class TaggerProtocol(Protocol):
    async def set_tags(self, file_path: Path, file_type: str, tags: Mapping[str, str]) -> None: ...


class LyricsGetterProtocol(Protocol):
    async def get_lyrics(self, query: str) -> str | None: ...


class MusicBrainzClientProtocol(Protocol):
    async def get_art(self, mbid: str) -> str | None: ...


class DirectoryScannerProtocol(Protocol):
    async def scan(self, path: Path) -> tuple[list[Path], list[Path]]: ...


class ConverterUtilProtocol(Protocol):
    async def convert_file(self, path: Path, codec: Codec | Any) -> None: ...


class DedupeFilesProtocol(Protocol):
    async def __call__(self, files: Sequence[Any]) -> Mapping[str, Any]: ...


class FingerprintFileProtocol(Protocol):
    async def __call__(self, path: Path) -> Mapping[str, Any]: ...


class ValidateFingerprintMetadataProtocol(Protocol):
    async def __call__(self, data: Mapping[str, Any]) -> Mapping[str, Any]: ...


class ExtractFPEntitiesProtocol(Protocol):
    async def __call__(self, data: Mapping[str, Any]) -> Mapping[str, Any]: ...


class MediaParseProtocol(Protocol):
    async def __call__(self, path: Path) -> Mapping[str, Any] | None: ...


class NormalizeProtocol(Protocol):
    async def __call__(self, *, file: Path, file_type: str) -> Awaitable[None]: ...


class GetFileTypeProtocol(Protocol):
    async def __call__(self, path: Path) -> str | None: ...


class AlbumArtCheckerUtilProtocol(Protocol):
    async def get_files_with_album_art(self) -> list[DBFile]: ...


class StackProtocol(Protocol):
    def add_counter(self, name: str, value: int = 1) -> None: ...


class DBInterface(Protocol):
    def get_session(self) -> AsyncGenerator[AsyncSessionLike, None]: ...
    async def register_picture(self, mbid: str, art_type: ArtType, save_path: Path) -> None: ...
